### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by JustaSimpleUser** [andrewaerospace/How-to-make-a-part-for-ksp#1]
Great start and I hope you continue to improve it.  The process and writing about it can't be easy.  I've covered only the first 50% or so.

### General

1. I would suggest increasing the font size to make it more readable, especially on smaller screens.
2. I was expecting a more step-by-step approach (my assumption, not necessarily your intent) so I find a lack of detail that might be helpful to someone tackling moding for the first time.  Perhaps a more comprehensive introductory paragraph explaining how detailed you are going to be.  If you want to retain the current level of detail, perhaps add a warning that what follows are very general steps, such as "make an engine in Blender".  There's a lot of ground to cover in that statement.

### Unity

1. Capitalize "unity"
2. The tool isn't called KSP PartTools.  Suggest "...download a plugin, called KSP PartTools, created by a KSP dev..."
3. You don't mention what TextMesh Pro" asset is so it's out of context and limits reader understand of what is required.
4. What about KSP 1.11?  I presume it's the same as 1.10 but to keep your document relevant for a little longer you should consider adding a Unity version for 1.11.

The remainder of the document is an interesting mix of detailed steps and general statements.

**Comment by andrewaerospace** [comment]
Okay, I will fix those things. It works for 1.11 too

**Comment by JustaSimpleUser** [comment]
Closed.  Out of date.
